# Generated by Django 5.2.4 on 2025-10-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
