# Generated by Django 5.2.4 on 2025-10-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctoravailability_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='date',
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
    ]
