# Generated by Django 5.2.4 on 2025-10-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_appointment_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='prescription',
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='max_patients',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
