# Generated by Django 5.2.4 on 2025-10-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_remove_appointment_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='fee',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='max_patients',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
