# Generated by Django 5.2.4 on 2025-10-03 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_patientprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time')},
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='max_patients',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='day',
            field=models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='patient_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.patientprofile'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_image', models.ImageField(upload_to='prescriptions/')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='test_reports/')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.appointment')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
    ]
