# Generated by Django 5.2.4 on 2025-10-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_rename_paid_appointment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8),
        ),
    ]
