# Generated by Django 5.2.4 on 2025-10-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_doctoravailability_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
