# Generated by Django 5.2.4 on 2025-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_appointment_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription_image',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='test_reports/'),
        ),
    ]
