# Generated by Django 5.2.4 on 2025-10-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_appointment_prescription_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_image',
            field=models.FileField(upload_to='prescriptions/'),
        ),
    ]
