# Generated by Django 5.2.4 on 2025-10-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_alter_prescription_prescription_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='prescription_image',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_image',
            field=models.ImageField(upload_to='prescriptions/'),
        ),
    ]
